### ISSUE TITLE
No way to be notified on \x01 ACTION messages

### ISSUE THREAD

**Issue by LiraNuna** [Shizmob/pydle#121]
the custom "extension"(?) messages that are generated via `/me` in most clients are not given to `on_message` or `on_raw_privmsg` even though it is a PRIVMSG command. The content of the message is `\x01ACTION action\x0x01` where `\x01` is the literal byte with value 1. 

I could not find anything in the docs about how to be notified about it.

**Comment by theunkn0wn1** [comment]
Testing this against release 0.9.1, it does appear to be captured by `on_raw_privmsg`.
Client implementation:
```py
    async def on_raw_privmsg(self, *args, **kwargs):
        LOG.debug(f"privmsg ::: {args} {kwargs}")
        await super().on_raw_privmsg(*args, **kwargs)
```
log output (verbose)

```

<2019-08-04 20:20:34 MechaClient:localhost> [DEBUG] << :orion!orion@BE9A4370.314F469.E00AF3E3.IP PRIVMSG #unkn0wndev :ACTION yawns
<2019-08-04 20:20:34 mecha.src.mechaclient> [DEBUG] privmsg ::: (<pydle.features.ircv3.tags.TaggedMessage object at 0x000001AF0284CEB8>,) {}
```

I will do some investigation to see if there is a less low-level callback that exposes these events, as they do not appear to get passed to `on_message`.
It is currently unclear if this is by design or due to a bug.

**Comment by Shizmob** [comment]
> On Aug 5, 1 Reiwa, at 05:25, Joshua Salzedo <notifications@github.com> wrote:
> 
> Testing this against release 0.9.1, it does appear to be captured by on_raw_privmsg.
> Client implementation:
> 
>     async def on_raw_privmsg(self, *args, **kwargs
> ):
>         
> LOG.debug(f"privmsg ::: {args} {kwargs}"
> )
>         
> await super().on_raw_privmsg(*args, **kwargs)
> log output (verbose)
> 
> 
> <2019-08-04 20:20:34 MechaClient:localhost> [DEBUG] << :orion!orion@BE9A4370.314F469.E00AF3E3.IP PRIVMSG #unkn0wndev :�ACTION yawns�
> <2019-08-04 20:20:34 mecha.src.mechaclient> [DEBUG] privmsg ::: (<pydle.features.ircv3.tags.TaggedMessage object at 0x000001AF0284CEB8>,) {}
> 
> I will do some investigation to see if there is a less low-level callback that exposes these events, as they do not appear to get passed to on_message.
> It is currently unclear if this is by design or due to a bug.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

This feature is called CTCP, and it’s transformed by the client into `on_ctcp_action(source, target, message)`,
or `on_ctcp(source, target, type, message)` if no specific action handler exists.

**Comment by LiraNuna** [comment]
`on_ctcp_action` worked! Thank you for clarifying, I was not aware actions are a part of CTCP, given that in the protocol they are a simple `PRIVMSG` to the channel with odd formatting.
