### ISSUE TITLE
Pydle does not expose real IPs/hostnames, even if it can see them in addition to vhost.

### ISSUE THREAD

**Issue by kenneaal** [Shizmob/pydle#136]
Pydle's users dict and whois dict does not contain a "connecting from" to hold the user's real IP on servers that use cloaking or VHosts. It only exposes their vhost or cloaked IP. When pydle has sufficient privileges to see these IPs, it should provide access to them somewhere.

**Comment by theunkn0wn1** [comment]
This information is provided by an `RPL_WHOISHOST` response from UnrealIRCd servers, so it wouldn't be a thing Pydle would parse by default. That being said, I have opened #138 which adds an optional feature that will enable support for this feature request.

You can enable this feature by importing and inheriting from it as per the documentation.

**Comment by theunkn0wn1** [comment]
Closed via #138
