### ISSUE TITLE
invalid version limiation in pyproject.toml

### ISSUE THREAD

**Issue by DimStar77** [Shizmob/pydle#181]
https://github.com/Shizmob/pydle/blob/504459a0640712ac244a461541af943c5296ef0d/pyproject.toml#L11

According to the poetry docs, the correct syntax would be:
`python = ">=3.6,<3.10"` (comma, not semicolon)

with poetry 1.2.x this has become fatal and returns this build error:

[   23s]   poetry.core.constraints.version.exceptions.ParseConstraintError: Could not parse version constraint: >=3.6;<3.10

**Comment by theunkn0wn1** [comment]
Yikes, was this always invalid?

**Comment by DimStar77** [comment]
> Yikes, was this always invalid?

In think so - the limitation `<3.10` had simply been ignored as far as I could see
