### ISSUE TITLE
Pydle can't keep track of accounts on networks using Atheme.

### ISSUE THREAD

**Issue by Polsaker** [Shizmob/pydle#34]
Currently, pydle assumes that users are [logged out when they change nicks](https://github.com/Shizmob/pydle/blob/master/pydle/features/account.py#L17), but this only happens in networks using Anope (as far as I know).

This breaks account tracking in freenode, espernet and some other networks. A solution could be to _not_ assume that users are logged out when they change nicks and instead depend on `account-notify` or to add an option to tell pydle when it shouldn't assume that users are logged out when they change nicks.

**Comment by dewiniaid** [comment]
As it turns out, this was actually affecting Anope services.  I incorrectly assumed Atheme because it was providing Atheme-style WHOIS, but I recall the Nickserv docs mentioning Anope.

**Comment by Polsaker** [comment]
Well, as it is it should work correctly in Anope networks. It only breaks account tracking in networks using Anope (or any other services package that doesn't log out users when they change nicks)

**Comment by Shizmob** [comment]
Thanks for reporting! I'll fix it this afternoon.

**Comment by Shizmob** [comment]
Would the just-pushed commit work for you? I made it simply check the registration status again, since I don't want to depend on account-notify being present for accurate reporting.

**Comment by Polsaker** [comment]
Is it possible to remove the check and the unsetting if account-notify is there?

**Comment by Shizmob** [comment]
Would this work for you?

**Comment by Polsaker** [comment]
Yes, that should work. Thank you!
