### ISSUE TITLE
Timeout handler waits for too long

### ISSUE THREAD

**Issue by EnKrypt** [Shizmob/pydle#38]
Coming from issue #37 - Read it for the train of discovery leading to this issue.

According to [this line](https://github.com/Shizmob/pydle/blob/f7d23244d278ad530907a1551b3066a3557933f1/pydle/client.py#L107) in `client.py` it will check for timeout every `PING_TIMEOUT / 2` seconds. But the second time that it checks for timeout, the current time elapsed will be at the same number of seconds as `PING_TIMEOUT` and thus will not trigger a timeout. So the checking function will have to run another time for the timeout to register.  
Meaning that the actual client will have to run for 1.5 times the seconds specified by `PING_TIMEOUT` before it can timeout.

I have no qualms with this approach but since the default value for `PING_TIMEOUT` is set to 720 seconds or 12 minutes, this means that the program will run for 18 minutes total before timing out. This is simply way too long.

I propose two solutions : Either change the default value of `PING_TIMEOUT` to 120 seconds. (I've tested this to be the best value along multiple servers).  
Or make the timeout register with an `equal to or less than` comparison so that the checker does not need to run a third time. This should be used in combination with a lower `PING_TIMEOUT` value as well to something like 180 seconds, because the default value of 12 minutes is still too much.

**Comment by EnKrypt** [comment]
@Shizmob : Please take a look. I'd also like to commit any changes regarding this issue myself via a PR if that's not a problem.

**Comment by Shizmob** [comment]
Yeah, makes sense. The initial high value was chosen because I did not want a pydle client to time-out willy nilly if someone's TCP connectivity dropped for a few minutes, but I can see the advantages of a lower timeout. I think combining the two solutions is the best approach, as the comparison combined with the timing of the ping-check is a clear bug.

**Comment by Shizmob** [comment]
Any PR is welcome, of course! I might not be able to look at it in the next few days however due some real life business.

**Comment by EnKrypt** [comment]
Alright, I've made a PR with a fix.

I've significantly modified the logic in which the timeouts were internally handled, so some reviewing might be recommended. I have however already tested this to work well and as expected on several servers.
