### ISSUE TITLE
OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by johnlage** [Shizmob/pydle#47]
Hello, I'm trying to disconnect a client in a pool (from another client in that pool), when I attempt to do so, I get this error, "OSError: [WinError 10038] An operation was attempted on something that is not a socket", presumably because its not removing the socket from the eventloop in time, or something like that. What can I do to prevent this error. (Python 3.5.2, Windows 10) OK, I just tested in Cygwin, and it gives "ValueError: I/O operation on closed file". (Python 3.4.3, Cygwin on Windows 10)
EDIT: I should rephrase, it allows the disconnect, and continues running the function, but after the funtion finishes, it errors.

**Comment by johnlage** [comment]
OK, new discovery, It appears that attempting to disconnect any single client from any running pool causes a crash with this error.

**Comment by johnlage** [comment]
Sorry for the spam, but it seems that it is any disconnect from any client with or without a pool. I just had a client ping timeout, and immediately error with this message, before having a chance to attempt to reconnect.

**Comment by Shizmob** [comment]
Hi! Terribly sorry for the delayed response, but I have been searching for a good solution to this problem for a while.

I’ve been working on a version based on the (in my opinion) better [asyncio](https://docs.python.org/3/library/asyncio.html) library.
It is far from perfect and contains numerous bugs right now as it’s in initial porting state,
but I would be very grateful if you could check if that specific error at least disappears with that port. :)

I’ve pushed it to the `asyncio` branch here: https://github.com/Shizmob/pydle/tree/asyncio

Thanks for using Pydle and reporting the issue in question!

**Comment by Harmon758** [comment]
This is great! I've been having issues with the current asynchronous system, and I've had good experiences with asyncio. Hopefully, it'll be a smooth process porting it to asyncio.
Thanks for working on this.

**Comment by johnlage** [comment]
Seems to be working great, everything else continues to run like normal if a single client is d/ced. Thanks!

**Comment by Shizmob** [comment]
I've meanwhile finished the initial port in the asyncio branch, and the client should be properly async on all sides now. Sadly, this required one big invasive API change, namely that all callbacks are coroutines now, as well as most of the API functions.
