### ISSUE TITLE
Exceptions in coroutines never retrieved

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#48]
When an exception is thrown inside a coroutine event, the exception doesn't make it to stdout. The exception just seems to be silently dropped, and the coroutine doesn't continue execution for that event.
Sometimes, on ending the program, there'll be an error like 
`ERROR:tornado.application:Future <pydle.async.Future object at 0x02FB3B30> exception was never retrieved`
which includes the traceback and exception that was thrown.

**Comment by Shizmob** [comment]
Hi, thanks for reporting! This should be fixed in the `asyncio` branch as well by now

**Comment by Harmon758** [comment]
Just tested it out, and this has indeed been fixed. Thank you!
