### ISSUE TITLE
Can't connect to ZNC - no way to send server passwords

### ISSUE THREAD

**Issue by dawtmaytrikx** [Shizmob/pydle#72]
So I'm trying to connect pydle to a ZNC server, but there doesn't seem to be a way to send server passwords. Unfortunately TLS cert auth also won't work because ZNC still requires a password to be sent, even if it's just a random string or blank.

> Unknown command: [irc.znc.in] 464 ['username/servername:password', 'Password required']

**Comment by Shizmob** [comment]
Strange, that should work. Have you tried passing `password=''` to the `client.connect()` call?

**Comment by dawtmaytrikx** [comment]
I did now and it works, thanks! :) I couldn't find this in the documentation.
