### ISSUE TITLE
Code example in README not works

### ISSUE THREAD

**Issue by SilverRainZ** [Shizmob/pydle#85]
In [Basic Usage section](https://github.com/Shizmob/pydle#basic-usage), it seems that the `pydle.Client` does not have a `run` method?

```
$ python -V
Python 3.6.0

$ python -c 'import pydle; print(pydle.__version__)'
0.8.4

$ cat test.py
import pydle

# Simple echo bot.
class MyOwnBot(pydle.Client):
    async def on_connect(self):
         await self.join('#bottest')

    async def on_message(self, target, source, message):
         await self.message(target, message)

client = MyOwnBot('MyBot', realname='My Bot')
client.run('irc.rizon.net', tls=True, tls_verify=False)

$ python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    client.run('irc.rizon.net', tls=True, tls_verify=False)
  File "/home/la/.pyenv/versions/venv/lib/python3.6/site-packages/pydle/client.py", line 430, in __getattr__
    raise AttributeError(attr)
AttributeError: run
```

**Comment by Harmon758** [comment]
Based on your error, you're using the tagged v0.8.4 release.
`Client.run` was added in the asyncio branch with https://github.com/Shizmob/pydle/commit/db6cdfbe3334c46e4da9f647decc467e36327cd0.
It was then merged into the master branch after the v0.8.4 release with https://github.com/Shizmob/pydle/commit/801d9e8843fd552e3e6ecf49cf9bc33b971dfa29.
For basic usage with the v0.8.4 release, see https://github.com/Shizmob/pydle/tree/v0.8.4#basic-usage.
In the future, please make sure you're using the most recent development version when reporting issues.
