### ISSUE TITLE
RuntimeWarning: coroutine 'RFC1459Support._registration_completed' was never awaited

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#87]
This occurs on 
https://github.com/Shizmob/pydle/blob/a7053805cfbeec78ce7d30ea359a775c5ea1200e/pydle/features/rfc1459/client.py#L943 as `_registration_completed` is a coroutine that's not awaited:
https://github.com/Shizmob/pydle/blob/a7053805cfbeec78ce7d30ea359a775c5ea1200e/pydle/features/rfc1459/client.py#L217

**Comment by theunkn0wn1** [comment]
Resolved for v0.9.0

**Comment by LiraNuna** [comment]
This is still happening to me on 0.9.1

**Comment by theunkn0wn1** [comment]
@LiraNuna Looks like your issue is unique to this one, would you mind making a new issue ticket?

Looking at the source you are indeed correct about a missing await, however I can also see a few issues with the `ctcp_reply` that I will need to resolve to make this work properly.

**Comment by theunkn0wn1** [comment]
Actually, looks like i already resolved these in #118 , I will have a bug fix released shortly.

**Comment by LiraNuna** [comment]
Thank you for the quick reply!

**Comment by theunkn0wn1** [comment]
@LiraNuna should be resolved in the release `0.9.2`, please upgrade your local pydle version and verify your issue is now resolved?

**Comment by LiraNuna** [comment]
Verified! Thank you for the quick fix!

**Comment by theunkn0wn1** [comment]
No worries, my apologies for not releasing the fix sooner 😓
