### ISSUE TITLE
Support dropped for Python 3.4

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#91]
#79 dropped support for Python 3.4 with `async def`/`await` syntax, yet the README still says the library is for Python 3.4+

**Comment by theunkn0wn1** [comment]
Readme updated in 
https://github.com/Shizmob/pydle/commit/2bfa42e37291c0f786e822013ab6c6cf59643bf3

Python 3.4 is officially unsupported as of v0.9.0
