### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#94]
The [most recent build](https://readthedocs.org/projects/pydle/builds/) for Read the Docs was over a year ago.

**Comment by theunkn0wn1** [comment]
Read the docs build is going to take some time, I might need to contact @Shizmob to get access to its configuration.

**Comment by theunkn0wn1** [comment]
@Shizmob would it be possible to gain access to RTD's documentation so i can bring that up to date? 
If not, would it be possible for you to manually trigger a build?

**Comment by Shizmob** [comment]
Just added you. 👍

**Comment by theunkn0wn1** [comment]
thanks. 👍 
Build succeeded successfully, and I can confirm the recent documentation additions are now visible. 
At this point the documentation is up-to-date so I will close this ticket now.
