### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#95]
This occurs on:
https://github.com/Shizmob/pydle/blob/a7053805cfbeec78ce7d30ea359a775c5ea1200e/pydle/features/rfc1459/parsing.py#L148 in Python 3.7 due to https://github.com/python/cpython/pull/5460

**Comment by theunkn0wn1** [comment]
Fixed for v0.9.0, release pending.
